[book]
authors = ["Defender"]
language = "en"
multilingual = false
src = "src"
title = "Open Memetics Institute"

[output.html]
edit-url-template = "https://github.com/DefenderOfBasic/open-memetics-institute/edit/main/{path}"
default-theme = "ayu"

[output.html.print]
enable = false 

[output.html.fold]
enable = true
level = 0 